version: "2.27.1"

networks:
  my-network:
    driver: bridge

services:

  product_db:
    image: postgres:16-alpine
    restart: always
    container_name: db
    env_file:
      - .prod_conf
    ports:
      - '5433:5432'
    networks:
      - my-network

  web:
    build:
      context: backend
    container_name: web
    command: >
      sh -c "gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .prod_conf
    ports:
      - '8000:8000'
    depends_on:
      - product_db
    networks:
      - my-network

  nginx:
    container_name: nginx
    image: nginx:alpine
    depends_on:
      - web
    ports:
      - '80:80'
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf
      - ./backend/app/static:/app/static
    networks:
      - my-network